### ISSUE TITLE
Add subdomains of language

### ISSUE THREAD

**Issue by By-oussef** [ZenPhoto20/Website#10]
Add subdomains for each language of NPG.

fr.netphotographics.org     French
es.netphotographics.org    Spanish
it.netphotographics.org      Italian
ja.netphotographics.org      Japanese

**Comment by sbillard** [comment]
These links already work. What is missing are the translations. There are two needs here. The first is native translations of the. Site specific content. The other is the standard npg getext translations. Both require native speaker volunteers.

**Comment by By-oussef** [comment]
I can provide translation for french, spanish and italian.

**Comment by sbillard** [comment]
Ok

**Comment by By-oussef** [comment]
Hello @sbillard  can you open this topic.

**Comment by sbillard** [comment]
For what purpose? The subdomains are already present, what is missing is translations. You could open tickets for each missing translation, but that would also be pointless. If someone will volunteer the translations then they can open a ticket to get them installed. otherwise tickets such as this are simply a waste of time. 

I do not wish to wish to waste my time, so please use careful consideration on the tickets you produce. If they continue to be pointless and useless you stand the chance of being blocked from further discourse.
